/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VirtualCatalogRouteImport } from './routes/virtual-catalog'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CelebrityLooksRouteImport } from './routes/celebrity-looks'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as BestsellersRouteImport } from './routes/bestsellers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard/wishlist'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard/security'
import { Route as DashboardReturnsRouteImport } from './routes/dashboard/returns'
import { Route as DashboardRecentlyViewedRouteImport } from './routes/dashboard/recently-viewed'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardAddressesRouteImport } from './routes/dashboard/addresses'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCollectionsRouteImport } from './routes/admin/collections'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualCatalogRoute = VirtualCatalogRouteImport.update({
  id: '/virtual-catalog',
  path: '/virtual-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrityLooksRoute = CelebrityLooksRouteImport.update({
  id: '/celebrity-looks',
  path: '/celebrity-looks',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const BestsellersRoute = BestsellersRouteImport.update({
  id: '/bestsellers',
  path: '/bestsellers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/dashboard/wishlist',
  path: '/dashboard/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/dashboard/support',
  path: '/dashboard/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/dashboard/security',
  path: '/dashboard/security',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReturnsRoute = DashboardReturnsRouteImport.update({
  id: '/dashboard/returns',
  path: '/dashboard/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRecentlyViewedRoute = DashboardRecentlyViewedRouteImport.update({
  id: '/dashboard/recently-viewed',
  path: '/dashboard/recently-viewed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/dashboard/orders',
  path: '/dashboard/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAddressesRoute = DashboardAddressesRouteImport.update({
  id: '/dashboard/addresses',
  path: '/dashboard/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/admin/collections',
  path: '/admin/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bestsellers': typeof BestsellersRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/celebrity-looks': typeof CelebrityLooksRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/lookbook': typeof LookbookRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/virtual-catalog': typeof VirtualCatalogRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recently-viewed': typeof DashboardRecentlyViewedRoute
  '/dashboard/returns': typeof DashboardReturnsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bestsellers': typeof BestsellersRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/celebrity-looks': typeof CelebrityLooksRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/lookbook': typeof LookbookRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/virtual-catalog': typeof VirtualCatalogRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recently-viewed': typeof DashboardRecentlyViewedRoute
  '/dashboard/returns': typeof DashboardReturnsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/support': typeof SupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bestsellers': typeof BestsellersRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/celebrity-looks': typeof CelebrityLooksRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/lookbook': typeof LookbookRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/virtual-catalog': typeof VirtualCatalogRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recently-viewed': typeof DashboardRecentlyViewedRoute
  '/dashboard/returns': typeof DashboardReturnsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bestsellers'
    | '/book-appointment'
    | '/celebrity-looks'
    | '/checkout'
    | '/compare'
    | '/lookbook'
    | '/new-arrivals'
    | '/search'
    | '/shop'
    | '/virtual-catalog'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/support'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/dashboard/addresses'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/recently-viewed'
    | '/dashboard/returns'
    | '/dashboard/security'
    | '/dashboard/support'
    | '/dashboard/wishlist'
    | '/product/$id'
    | '/admin/'
    | '/blog/'
    | '/collections/'
    | '/dashboard/'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bestsellers'
    | '/book-appointment'
    | '/celebrity-looks'
    | '/checkout'
    | '/compare'
    | '/lookbook'
    | '/new-arrivals'
    | '/search'
    | '/shop'
    | '/virtual-catalog'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/support'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/dashboard/addresses'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/recently-viewed'
    | '/dashboard/returns'
    | '/dashboard/security'
    | '/dashboard/support'
    | '/dashboard/wishlist'
    | '/product/$id'
    | '/admin'
    | '/blog'
    | '/collections'
    | '/dashboard'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bestsellers'
    | '/book-appointment'
    | '/celebrity-looks'
    | '/checkout'
    | '/compare'
    | '/lookbook'
    | '/new-arrivals'
    | '/search'
    | '/shop'
    | '/virtual-catalog'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/support'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/dashboard/addresses'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/recently-viewed'
    | '/dashboard/returns'
    | '/dashboard/security'
    | '/dashboard/support'
    | '/dashboard/wishlist'
    | '/product/$id'
    | '/admin/'
    | '/blog/'
    | '/collections/'
    | '/dashboard/'
    | '/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BestsellersRoute: typeof BestsellersRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  CelebrityLooksRoute: typeof CelebrityLooksRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  LookbookRoute: typeof LookbookRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  VirtualCatalogRoute: typeof VirtualCatalogRoute
  WishlistRoute: typeof WishlistRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  DashboardAddressesRoute: typeof DashboardAddressesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRecentlyViewedRoute: typeof DashboardRecentlyViewedRoute
  DashboardReturnsRoute: typeof DashboardReturnsRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  ProductIdRoute: typeof ProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-catalog': {
      id: '/virtual-catalog'
      path: '/virtual-catalog'
      fullPath: '/virtual-catalog'
      preLoaderRoute: typeof VirtualCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrity-looks': {
      id: '/celebrity-looks'
      path: '/celebrity-looks'
      fullPath: '/celebrity-looks'
      preLoaderRoute: typeof CelebrityLooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestsellers': {
      id: '/bestsellers'
      path: '/bestsellers'
      fullPath: '/bestsellers'
      preLoaderRoute: typeof BestsellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wishlist': {
      id: '/dashboard/wishlist'
      path: '/dashboard/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/dashboard/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/returns': {
      id: '/dashboard/returns'
      path: '/dashboard/returns'
      fullPath: '/dashboard/returns'
      preLoaderRoute: typeof DashboardReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/recently-viewed': {
      id: '/dashboard/recently-viewed'
      path: '/dashboard/recently-viewed'
      fullPath: '/dashboard/recently-viewed'
      preLoaderRoute: typeof DashboardRecentlyViewedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/addresses': {
      id: '/dashboard/addresses'
      path: '/dashboard/addresses'
      fullPath: '/dashboard/addresses'
      preLoaderRoute: typeof DashboardAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/admin/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BestsellersRoute: BestsellersRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  CelebrityLooksRoute: CelebrityLooksRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  LookbookRoute: LookbookRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  VirtualCatalogRoute: VirtualCatalogRoute,
  WishlistRoute: WishlistRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  BlogSlugRoute: BlogSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  DashboardAddressesRoute: DashboardAddressesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRecentlyViewedRoute: DashboardRecentlyViewedRoute,
  DashboardReturnsRoute: DashboardReturnsRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  ProductIdRoute: ProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
